env:
  global:
    - BUILD_TYPE=build
language: node_js
node_js:
- '8'
install:
- yarn add global eslint
- yarn add global babel-eslint
- yarn add global eslint-plugin-react
- yarn add global eslint-plugin-mocha
- yarn add global eslint-config-synacor
- yarn add global firebase-tools
script:
- yarn run lint
- yarn run test
- yarn run build
- gulp release
cache: yarn

deploy:
  provider: firebase
  token:
    secure: "hrVxWzG76yv+gEv1STOb2jDNDBMvwAYwMQtTFIgl1EsGF5a8erXTsdCRSbSgQiQTeBoqhygGW9dChicCHHPVPP9+seyusGsGgaqpu6oQxJNkqFPBZ9sl3AX5F1C9g08j8owe68hqLhJfgIoRP8PBcMWIgTQC7e6Mg4X6+/KkL9VPBVbL3tnux+L2Uo5jT1D+LK/vHZ8uIS1Nrm5DXtUPCx1hFLSjuJRX4/Tl4Nn8Fr64X0nLd8skWTRPN5xBHoHXL85ZkQ7zBn3ZAywVvEBzxJBdv99hfVRcphnJ5pQCiyHDv6b2hwZV6w39QI+gzZlTsPEI17kWA+dgyGyp9zrnXJqXcMj60EdDw/SrI2O8yhZkMa15EMwWbn7JmaNkW5C0kzuwGbxCpsL1JRPFl3QovoqeXYrGNJ9IKkzRxIeU2ntztzvfG0si4vr/mcDOVJyiLqaR71qqM1jFxxBrKyEuDCWl0ClWv56FcWenARe2k+pzM4JiO56bzLnwCDp0YDdoSqhXhcKgxCk4FwZGEzAVo4igkFdhFM4yQ9HIWJOUP90EzKWI4ENrds/xpyh3et4t/nvH7pHlczZ45FxgFkQ4znVcDH2F3C7Di3ITXWM3EKb3I6Euwpe1x6XddrmdJUTIpYKsiQTPBsAYWK9f+vsFquXxXNxvVT0YGeoF036VDCQ="
  skip_cleanup: true
  project: "default"
  on:
    repo: ZenUml/web-sequence
    all_branches: true
    condition: $BUILD_TYPE = deploy
